version: '3.1'

services:
  db:
    image: mysql:8.1
    container_name: local-mysql-8-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: local-phpmyadmin
    restart: always
    ports:
      - "3307:80"
    environment:
      - PMA_ARBITRARY=1